DEEPSORT:
  REID_CKPT: "/mnt/358ecbeb-dc8c-461f-8854-c78c448ac39c/AgriCPS-srihari/LocalizeSORT/deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  